### ISSUE TITLE
Use attrs when a class calls `super`

### ISSUE THREAD

**Issue by felipedau** [AnemoneLabs/unmessage#50]
I could not use attrs in the `Introduction` class because it inherits from `Thread` and I have not found a way to call `super`. Example:

```python
>>> @attr.s
... class T(Thread, object):
...     def __attr_post_init__(self):
...             super(T, self).__init__()
... 
>>> t = T()
>>> t.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/threading.py", line 737, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
```

@meejah, do you have an idea on how to do this?

**Comment by felipedau** [comment]
As I continued working on #21, I noticed there was no need to subclass `Thread` in `Introduction` and now there is no need to fix this. Anyways, here is some useful info:

- When I tried to reproduce the error, I made a mistake: wrote `__attr_post_init__` instead of `__attrs_post_init__`
- That method would never be called, along with `super().__init__()` inside it
- Due to the mistake, I thought that `Thread.__init__()` not being called was the issue I had in the first place 
- When fixing the typo, the real issue is actually `TypeError: unhashable type`
- Passing `hash=True` to `@attr.s()` makes it hashable
